#-------------------------------
# General Site Settings

title: Personal Portfolio Theme
description: Powered by Jekyll and GitHub Pages
email: l.nguyen.paul@gmail.com

menu:
- {name: 'Projects', url: ''}
- {name: 'Blog', url: 'blog.html'}
- {name: 'About', url: 'about.html'}
- {name: 'Contact', url: 'contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/115391695226276326378'
  rel-publisher: 'https://plus.google.com/u/0/115391695226276326378'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

about: >
  # Personal Portfolio Theme

  This is my personal portfolio theme that I built from the ground up, using the [DevTips Starter Kit](http://devtipsstarterkit.com/) as a foundation for starting, and following closely the amazing tutorial by [Travis Neilson over at DevTips](https://www.youtube.com/watch?v=T6jKLsxbFg4&list=PL0CB3OvPhDA_STygmp3sDenx3UpdOMk7P). You can [check out the demo](lenpaul.github.io/portfolio-theme/), and [fork the repository](https://github.com/LeNPaul/portfolio-theme/fork), to get started.

contact: >
  # Contact

  You may contact me [through my email](mailto:l.nguyen.paul@gmail.com) or [tweet at me](https://twitter.com/intent/tweet?text=%40paululele) if you have any questions or would like to bring up any issues.

#-------------------------------
# Work Section

projects:
- {name: 'Project One', folder: 'proj-1', file: 'work/proj-1.html'}
- {name: 'Project Two', folder: 'proj-2', file: 'work/proj-2.html'}
- {name: 'Project Three', folder: 'proj-3', file: 'work/proj-3.html'}
- {name: 'Project Four', folder: 'proj-4', file: 'work/proj-4.html'}
- {name: 'Project Five', folder: 'proj-5', file: 'work/proj-5.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'github', link: 'https://www.github.com/lenpaul'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/'}
- {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
